# Generated by Django 5.2.15 on 2026-06-08 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_membership_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('kind', models.CharField(choices=[('CERT', 'Certificado (monitoreo)'), ('REPORT', 'Reporte')], max_length=8, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('blocks', models.JSONField(blank=True, default=list, verbose_name='Bloques')),
                ('is_default', models.BooleanField(default=False, verbose_name='Predeterminada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_created', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Etiqueta organizativa opcional (no controla acceso).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to='teams.team')),
            ],
            options={
                'verbose_name': 'Plantilla de correo',
                'verbose_name_plural': 'Plantillas de correo',
                'ordering': ['kind', 'name'],
            },
        ),
    ]
