# Generated by Django 5.2.15 on 2026-06-06 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('severity', models.CharField(choices=[('POR_VENCER', 'Por vencer'), ('CRITICO', 'Crítico'), ('VENCIDO', 'Vencido'), ('ERROR', 'Error')], max_length=15, verbose_name='Severidad')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('RESOLVED', 'Resuelta'), ('SNOOZED', 'Pospuesta')], default='OPEN', max_length=10, verbose_name='Estado')),
                ('message', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta')),
                ('snoozed_until', models.DateTimeField(blank=True, null=True, verbose_name='Pospuesta hasta')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='certificates.certificate')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('channel', models.CharField(choices=[('PLATFORM', 'Plataforma'), ('EMAIL', 'Correo'), ('WEBHOOK', 'Webhook')], max_length=10, verbose_name='Canal')),
                ('target', models.CharField(blank=True, max_length=500, verbose_name='Destino')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviada'), ('FAILED', 'Fallida')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.alert')),
            ],
            options={
                'verbose_name': 'Envío de alerta',
                'verbose_name_plural': 'Envíos de alerta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('webhook_type', models.CharField(choices=[('TEAMS', 'Microsoft Teams'), ('SLACK', 'Slack'), ('GENERIC', 'Genérico')], max_length=10, verbose_name='Tipo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('url', models.URLField(max_length=500, verbose_name='URL del webhook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('team', models.ForeignKey(blank=True, help_text='Vacío = integración global (todos los grupos).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='teams.team')),
            ],
            options={
                'verbose_name': 'Integración webhook',
                'verbose_name_plural': 'Integraciones webhook',
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='alerts_aler_status_58cd09_idx'),
        ),
    ]
