# Generated by Django 5.2.15 on 2026-06-07 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookintegration',
            name='rich_format',
            field=models.BooleanField(default=False, help_text='Envía tarjetas/bloques con formato (Teams/Slack) en vez de texto plano.', verbose_name='Formato enriquecido'),
        ),
        migrations.CreateModel(
            name='AlertUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Limpiada del panel')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de alerta por usuario',
                'verbose_name_plural': 'Estados de alerta por usuario',
                'constraints': [models.UniqueConstraint(fields=('alert', 'user'), name='unique_alert_user_state')],
            },
        ),
    ]
