# Generated by Django 5.2.15 on 2026-06-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_migrate_read_by_to_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertdelivery',
            name='channel',
            field=models.CharField(choices=[('PLATFORM', 'Plataforma'), ('EMAIL', 'Correo'), ('WEBHOOK', 'Webhook'), ('SMS', 'SMS')], max_length=10, verbose_name='Canal'),
        ),
    ]
