# Generated by Django 5.2.15 on 2026-06-07 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('language', models.CharField(default='es-do', max_length=10, verbose_name='Idioma')),
                ('timezone', models.CharField(default='America/Santo_Domingo', max_length=64, verbose_name='Zona horaria')),
                ('table_density', models.CharField(choices=[('COMODO', 'Cómodo'), ('COMPACTO', 'Compacto')], default='COMODO', max_length=10, verbose_name='Densidad de tablas')),
                ('notify_platform', models.BooleanField(default=True, verbose_name='Notificar en plataforma')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Notificar por correo')),
                ('notify_webhook', models.BooleanField(default=False, verbose_name='Notificar por webhook')),
                ('personal_webhook_url', models.URLField(blank=True, max_length=500, verbose_name='Webhook personal')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de perfil')),
                ('panel_cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='Panel limpiado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de usuario',
                'verbose_name_plural': 'Preferencias de usuario',
            },
        ),
    ]
