# Generated by Django 5.2.15 on 2026-06-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='avatar_choice',
            field=models.PositiveIntegerField(default=0, verbose_name='Avatar SVG'),
        ),
    ]
