# Generated by Codex on 2026-06-07

from django.db import migrations


def delete_uploaded_avatars(apps, schema_editor):
    UserPreferences = apps.get_model("accounts", "UserPreferences")
    for prefs in UserPreferences.objects.exclude(avatar="").exclude(avatar__isnull=True):
        try:
            prefs.avatar.delete(save=False)
        except Exception:
            # La migracion no debe bloquearse por archivos faltantes o storage no disponible.
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userpreferences_avatar_choice"),
    ]

    operations = [
        migrations.RunPython(delete_uploaded_avatars, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="userpreferences",
            name="avatar",
        ),
    ]
