# Generated by Codex on 2026-06-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userpreferences_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="notify_platform",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notify_email",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notify_webhook",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="personal_webhook_url",
        ),
    ]
