# Generated by Django 5.2.15 on 2026-06-08 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_strip_staff_from_non_superusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('secret', models.CharField(max_length=64, verbose_name='Secreto TOTP (Base32)')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo 2FA',
                'verbose_name_plural': 'Dispositivos 2FA',
            },
        ),
    ]
