# Generated by Django 5.2.15 on 2026-06-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_twofactordevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contraseña cambiada'),
        ),
    ]
