# Generated by Django 5.2.15 on 2026-06-06 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('domain', models.CharField(max_length=253, verbose_name='Dominio / host')),
                ('port', models.PositiveIntegerField(default=443, verbose_name='Puerto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('alert_threshold_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Umbral de alerta (días)')),
                ('critical_threshold_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Umbral crítico (días)')),
                ('notify_platform', models.BooleanField(blank=True, null=True, verbose_name='Alertar en plataforma')),
                ('notify_email', models.BooleanField(blank=True, null=True, verbose_name='Alertar por correo')),
                ('notify_webhook', models.BooleanField(blank=True, null=True, verbose_name='Alertar por webhook')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Etiquetas')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por vencer'), ('CRITICO', 'Crítico'), ('VENCIDO', 'Vencido'), ('ERROR', 'Error'), ('SIN_CHEQUEAR', 'Sin chequear')], default='SIN_CHEQUEAR', max_length=15, verbose_name='Estado')),
                ('days_left', models.IntegerField(blank=True, null=True, verbose_name='Días restantes')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('issuer', models.CharField(blank=True, max_length=255, verbose_name='Emisor')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Sujeto')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Último chequeo')),
                ('next_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Próximo chequeo')),
                ('last_error', models.TextField(blank=True, verbose_name='Último error')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_created', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='teams.team')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='CertificateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('checked_at', models.DateTimeField(verbose_name='Fecha de chequeo')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por vencer'), ('CRITICO', 'Crítico'), ('VENCIDO', 'Vencido'), ('ERROR', 'Error'), ('SIN_CHEQUEAR', 'Sin chequear')], max_length=15, verbose_name='Estado')),
                ('days_left', models.IntegerField(blank=True, null=True, verbose_name='Días restantes')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('issuer', models.CharField(blank=True, max_length=255, verbose_name='Emisor')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Sujeto')),
                ('serial', models.CharField(blank=True, max_length=128, verbose_name='Número de serie')),
                ('fingerprint_sha256', models.CharField(blank=True, max_length=95, verbose_name='Fingerprint SHA-256')),
                ('signature_algorithm', models.CharField(blank=True, max_length=64, verbose_name='Algoritmo de firma')),
                ('key_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño de clave')),
                ('san', models.JSONField(blank=True, default=list, verbose_name='SAN (dominios alternos)')),
                ('chain', models.JSONField(blank=True, default=list, verbose_name='Cadena de confianza')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Latencia (ms)')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='certificates.certificate')),
            ],
            options={
                'verbose_name': 'Chequeo',
                'verbose_name_plural': 'Chequeos',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='last_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificates.certificatecheck'),
        ),
        migrations.CreateModel(
            name='CertificateRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='certificates.certificate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
            },
        ),
        migrations.AddIndex(
            model_name='certificatecheck',
            index=models.Index(fields=['certificate', '-checked_at'], name='certificate_certifi_d0144d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='certificate_status_31e804_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['valid_to'], name='certificate_valid_t_18cb50_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('team', 'domain', 'port'), name='unique_team_domain_port'),
        ),
        migrations.AddConstraint(
            model_name='certificaterecipient',
            constraint=models.UniqueConstraint(fields=('certificate', 'email'), name='unique_certificate_email'),
        ),
    ]
