# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterecipient",
            name="alert_threshold_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Umbral original asociado a este correo en certapp_old.",
                null=True,
                verbose_name="Umbral legacy (días)",
            ),
        ),
    ]
