# Generated by Django 5.2.15 on 2026-06-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificaterecipient_alert_threshold_days'),
        ('mailtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mailtemplates.emailtemplate'),
        ),
    ]
