# Generated by Django 5.2.15 on 2026-06-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_email_template'),
        ('teams', '0003_membership_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='shared_certificates', to='teams.team', verbose_name='Grupos adicionales'),
        ),
    ]
