# Generated by Django 5.2.15 on 2026-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='notify_sms',
            field=models.BooleanField(blank=True, null=True, verbose_name='Alertar por SMS'),
        ),
    ]
