# Generated by Django 5.2.15 on 2026-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_certificate_notify_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silenciado hasta'),
        ),
    ]
