# Generated by Django 5.2.15 on 2026-06-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificate_snoozed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ubicación'),
        ),
    ]
