# Generated by Django 5.2.15 on 2026-06-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('org_name', models.CharField(default='CertForge', max_length=120, verbose_name='Nombre de la organización')),
                ('timezone', models.CharField(default='America/Santo_Domingo', max_length=64, verbose_name='Zona horaria')),
                ('default_language', models.CharField(default='es-do', max_length=10, verbose_name='Idioma')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='SMTP host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP puerto')),
                ('smtp_user', models.CharField(blank=True, max_length=255, verbose_name='SMTP usuario')),
                ('smtp_password', models.CharField(blank=True, max_length=255, verbose_name='SMTP password')),
                ('smtp_from', models.EmailField(blank=True, max_length=254, verbose_name='Remitente')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('check_interval_hours', models.PositiveIntegerField(default=24, verbose_name='Intervalo de chequeo (horas)')),
                ('connect_timeout', models.PositiveIntegerField(default=10, verbose_name='Timeout de conexión (s)')),
                ('retries', models.PositiveIntegerField(default=1, verbose_name='Reintentos')),
            ],
            options={
                'verbose_name': 'Configuración de la organización',
                'verbose_name_plural': 'Configuración de la organización',
            },
        ),
    ]
