# Generated by Django 5.2.15 on 2026-06-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='account_domain',
            field=models.CharField(blank=True, max_length=253, verbose_name='Dominio de la cuenta'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='ldap_enabled',
            field=models.BooleanField(default=False, verbose_name='LDAP habilitado'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='password_min_length',
            field=models.PositiveIntegerField(default=8, verbose_name='Longitud mínima de contraseña'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='preferred_check_window_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Ventana de chequeo (fin)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='preferred_check_window_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Ventana de chequeo (inicio)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='require_2fa',
            field=models.BooleanField(default=False, verbose_name='Exigir 2FA'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='session_timeout',
            field=models.PositiveIntegerField(default=0, verbose_name='Timeout de sesión (min)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='sso_enabled',
            field=models.BooleanField(default=False, verbose_name='SSO habilitado'),
        ),
    ]
