# Generated by Django 5.2.15 on 2026-06-07 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organizationsettings_account_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('scope', models.CharField(choices=[('full', 'Acceso total (lectura y escritura)'), ('read_only', 'Solo lectura')], default='read_only', max_length=10, verbose_name='Ámbito')),
                ('prefix', models.CharField(editable=False, max_length=12, verbose_name='Prefijo')),
                ('key_id', models.CharField(editable=False, max_length=24, unique=True, verbose_name='ID público')),
                ('hashed_key', models.CharField(editable=False, max_length=64, verbose_name='Hash de la clave')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clave de API',
                'verbose_name_plural': 'Claves de API',
                'ordering': ['-created_at'],
            },
        ),
    ]
