# Generated by Django 5.2.15 on 2026-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('enabled', models.BooleanField(default=False, verbose_name='LDAP habilitado')),
                ('server_uri', models.CharField(blank=True, help_text='ej. ldap://dc.ejemplo.local:389 o ldaps://dc:636', max_length=255, verbose_name='Servidor (URI)')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL (ldaps)')),
                ('start_tls', models.BooleanField(default=False, verbose_name='Usar StartTLS')),
                ('bind_dn', models.CharField(blank=True, max_length=255, verbose_name='Bind DN (cuenta de servicio)')),
                ('bind_password', models.CharField(blank=True, max_length=255, verbose_name='Bind password')),
                ('user_search_base', models.CharField(blank=True, help_text='ej. OU=Usuarios,DC=claro,DC=com,DC=do', max_length=255, verbose_name='Base de búsqueda de usuarios')),
                ('user_filter', models.CharField(blank=True, default='(mail={login})', help_text='Usa {login} como marcador. ej. (mail={login}) o (sAMAccountName={login})', max_length=255, verbose_name='Filtro de usuario')),
                ('email_attribute', models.CharField(default='mail', max_length=64, verbose_name='Atributo de correo')),
                ('connect_timeout', models.PositiveIntegerField(default=8, verbose_name='Timeout (s)')),
                ('last_test_at', models.DateTimeField(blank=True, null=True, verbose_name='Última prueba')),
                ('last_test_ok', models.BooleanField(blank=True, null=True, verbose_name='Última prueba OK')),
                ('last_test_message', models.CharField(blank=True, max_length=300, verbose_name='Resultado de la última prueba')),
            ],
            options={
                'verbose_name': 'Configuración LDAP',
                'verbose_name_plural': 'Configuración LDAP',
            },
        ),
        migrations.CreateModel(
            name='SmsGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('enabled', models.BooleanField(default=False, verbose_name='SMS habilitado')),
                ('ftp_host', models.CharField(blank=True, max_length=255, verbose_name='Host FTP')),
                ('ftp_user', models.CharField(blank=True, max_length=128, verbose_name='Usuario FTP')),
                ('ftp_password', models.CharField(blank=True, max_length=255, verbose_name='Password FTP')),
                ('default_number', models.CharField(blank=True, max_length=32, verbose_name='Número por defecto')),
                ('remote_filename', models.CharField(default='sms.log', max_length=64, verbose_name='Archivo remoto')),
            ],
            options={
                'verbose_name': 'Gateway SMS (FTP)',
                'verbose_name_plural': 'Gateway SMS (FTP)',
            },
        ),
    ]
