# Generated by Django 5.2.15 on 2026-06-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ldapconfiguration_smsgatewayconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('method', models.CharField(max_length=8, verbose_name='Método')),
                ('path', models.CharField(max_length=255, verbose_name='Ruta')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.apikey')),
            ],
            options={
                'verbose_name': 'Uso de API key',
                'verbose_name_plural': 'Uso de API keys',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['api_key', '-at'], name='core_apikey_api_key_b66613_idx')],
            },
        ),
    ]
