# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_apikeyusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="email_copy_enabled",
            field=models.BooleanField(default=True, verbose_name="Enviar copia global"),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="email_copy_address",
            field=models.EmailField(
                blank=True,
                default="alertas@ejemplo.local",
                max_length=254,
                verbose_name="Correo de copia global",
            ),
        ),
    ]
