# Generated by Django 5.2.15 on 2026-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orgsettings_email_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='org_name',
            field=models.CharField(default='CertManager', max_length=120, verbose_name='Nombre de la organización'),
        ),
    ]
