# Generated by Django 5.2.15 on 2026-06-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_organizationsettings_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='email_copy_address',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo de copia global'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='email_copy_enabled',
            field=models.BooleanField(default=False, verbose_name='Enviar copia global'),
        ),
    ]
