# Generated by Django 5.2.15 on 2026-06-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='password_expiry_days',
            field=models.PositiveIntegerField(default=90, verbose_name='Vigencia de contraseña (días)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='password_expiry_enabled',
            field=models.BooleanField(default=False, verbose_name='Expirar contraseñas'),
        ),
    ]
