# Generated by Django 5.2.15 on 2026-06-12 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_organizationsettings_password_expiry_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='preferred_check_window_end',
            field=models.TimeField(blank=True, default=datetime.time(5, 0), null=True, verbose_name='Ventana de chequeo (fin)'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='preferred_check_window_start',
            field=models.TimeField(blank=True, default=datetime.time(2, 0), null=True, verbose_name='Ventana de chequeo (inicio)'),
        ),
    ]
