# Generated by Django 5.2.15 on 2026-06-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='default_check_interval',
            field=models.PositiveIntegerField(default=24, verbose_name='Intervalo de chequeo por defecto (horas)'),
        ),
    ]
