# Generated by Django 5.2.15 on 2026-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_membership_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notify_sms',
            field=models.BooleanField(default=False, verbose_name='Alertar por SMS'),
        ),
    ]
