# Generated by Django 5.2.15 on 2026-06-13 01:43
"""Eliminación del rol Admin de grupo (decisión del Owner).

La gestión (grupos, miembros, alertas compartidas, plantillas) pasa a ser
exclusiva del Owner global. Las membresías ADMIN existentes se convierten en
CONTRIBUTOR (conservan la operación de certificados). Reversa: no-op (no se
puede saber quién era ADMIN).
"""
from django.db import migrations, models


def admins_to_contributors(apps, schema_editor):
    Membership = apps.get_model("teams", "Membership")
    Membership.objects.filter(role="ADMIN").update(role="CONTRIBUTOR")


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_notify_sms'),
    ]

    operations = [
        migrations.RunPython(admins_to_contributors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Visualizador'), ('CONTRIBUTOR', 'Colaborador')], default='VIEWER', max_length=12, verbose_name='Rol'),
        ),
    ]
