# Generated by Django 5.2.15 on 2026-06-06 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('template', models.CharField(choices=[('INVENTORY', 'Inventario de certificados'), ('EXPIRING', 'Próximos a vencer'), ('EXPIRED', 'Vencidos / con error'), ('HISTORY', 'Historial de chequeos'), ('BY_GROUP', 'Resumen por grupo')], max_length=15, verbose_name='Plantilla')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filtros del reporte (grupo, estado, ventana de vencimiento, etc.).', verbose_name='Filtros')),
                ('frequency', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], max_length=10, verbose_name='Frecuencia')),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10, verbose_name='Formato')),
                ('recipients', models.JSONField(blank=True, default=list, verbose_name='Destinatarios')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Vacío = todos los grupos (solo Owner).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='teams.team')),
            ],
            options={
                'verbose_name': 'Reporte programado',
                'verbose_name_plural': 'Reportes programados',
                'ordering': ['name'],
            },
        ),
    ]
