# Generated by Django 5.2.15 on 2026-06-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='formats',
            field=models.JSONField(blank=True, default=list, help_text='Lista de formatos simultáneos (PDF/EXCEL/CSV). Vacío = solo el formato principal.', verbose_name='Formatos a generar'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='send_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de envío'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='output_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10, verbose_name='Formato principal'),
        ),
    ]
