# Generated by Django 5.2.15 on 2026-06-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_scheduledreport_formats_scheduledreport_send_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, help_text="Solo para 'Cada N días' (p.ej. 15 o 30).", null=True, verbose_name='Intervalo (días)'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='start_date',
            field=models.DateField(blank=True, help_text="Ancla de la recurrencia. Para 'cada N días' la cuenta arranca aquí.", null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('EVERY_N_DAYS', 'Cada N días (desde una fecha)'), ('MONTHLY_DAY_1', 'El día 1 de cada mes')], max_length=15, verbose_name='Frecuencia'),
        ),
    ]
