# Generated by Django 5.2.15 on 2026-06-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtemplates', '0001_initial'),
        ('reports', '0003_scheduledreport_interval_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mailtemplates.emailtemplate'),
        ),
    ]
